### ISSUE TITLE
Just a newbie question

### ISSUE THREAD

**Issue by DavidMont** [51systems/gitlab-ci-android#1]
Can i get some examples how to use this, Its so good to have this kind of feature to have the same travis-feature like in gitlab-ci.

Thanks.

**Comment by 51systems** [comment]
Added an example `.gitlab-ci.yml` to the README

Docker hub doesn't like building the emulator images, it tends to timeout, so if you wish to use the emulator images you may have to build the docker images yourself.

**Comment by DavidMont** [comment]
Thanks
